name: Proteus main workflow

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install pip==23.0.1
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: pytest --cov-report=xml --cov=proteus

    - name: Upload coverage report to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml
